package UppercaseModule;

/**
* UppercaseModule/UppercaseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Uppercase.idl
* Wednesday, 6 May, 2026 9:19:03 PM IST
*/

public final class UppercaseHolder implements org.omg.CORBA.portable.Streamable
{
  public UppercaseModule.Uppercase value = null;

  public UppercaseHolder ()
  {
  }

  public UppercaseHolder (UppercaseModule.Uppercase initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UppercaseModule.UppercaseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UppercaseModule.UppercaseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UppercaseModule.UppercaseHelper.type ();
  }

}
