package UppercaseModule;


/**
* UppercaseModule/Uppercase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Uppercase.idl
* Wednesday, 6 May, 2026 9:19:03 PM IST
*/

public interface Uppercase extends UppercaseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Uppercase
